apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJmYXJvb3FpaSIsInBhc3N3b3JkIjoiQXNzYW5AMTIzIiwiYXV0aCI6IlptRnliMjl4YVdrNlFYTnpZVzVBTVRJeiJ9fX0=
