apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: flask-app-container
          image: farooqii/devops-all:flask-example-server
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://flaskUser:myserc@pass@postgresql-service:5432/flaskDB"
